<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EmployeeDirectory.Infrastructure</RootNamespace>
    <AssemblyName>EmployeeDirectory.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeDirectory.Application\EmployeeDirectory.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EmployeeDirectory.UnitTests" />
    <InternalsVisibleTo Include="EmployeeDirectory.IntegrationTests" />
  </ItemGroup>

</Project>
